project_id = "ojssezfjhdvvncsqyhyq"

[functions.import-shopify-products]
verify_jwt = false

[functions.scrape-update-products]
verify_jwt = false

[functions.import-customers]
verify_jwt = false

[functions.assign-tag-to-all-customers]
verify_jwt = false

[functions.pagarme-create-charge]
verify_jwt = true

[functions.pagarme-webhook]
verify_jwt = false

[functions.frenet-quote]
verify_jwt = true

[functions.integration-config]
verify_jwt = true

[functions.domains-verify]
verify_jwt = true

[functions.domains-provision]
verify_jwt = true

[functions.resolve-domain]
verify_jwt = false
