project_id = "ojssezfjhdvvncsqyhyq"

[functions.import-shopify-products]
verify_jwt = false

[functions.scrape-update-products]
verify_jwt = false

[functions.import-customers]
verify_jwt = false

[functions.assign-tag-to-all-customers]
verify_jwt = false

[functions.pagarme-create-charge]
verify_jwt = true

[functions.pagarme-webhook]
verify_jwt = false
